//! Auto-generated tile data from PNG tile images.
//! Each tile is a 16x24 monochrome bitmap (384 bytes).
//! 0 = background, 255 = foreground.
//!
//! Generated from shamogu/tiles/ directory.

/// Tile width in pixels.
pub const TILE_WIDTH: usize = 16;
/// Tile height in pixels.
pub const TILE_HEIGHT: usize = 24;

pub static FAVICON: &[u8; 384] = include_bytes!("../tiles_raw/favicon.bin");
pub static LETTER_0: &[u8; 384] = include_bytes!("../tiles_raw/letter-0.bin");
pub static LETTER_1: &[u8; 384] = include_bytes!("../tiles_raw/letter-1.bin");
pub static LETTER_2: &[u8; 384] = include_bytes!("../tiles_raw/letter-2.bin");
pub static LETTER_3: &[u8; 384] = include_bytes!("../tiles_raw/letter-3.bin");
pub static LETTER_4: &[u8; 384] = include_bytes!("../tiles_raw/letter-4.bin");
pub static LETTER_5: &[u8; 384] = include_bytes!("../tiles_raw/letter-5.bin");
pub static LETTER_6: &[u8; 384] = include_bytes!("../tiles_raw/letter-6.bin");
pub static LETTER_7: &[u8; 384] = include_bytes!("../tiles_raw/letter-7.bin");
pub static LETTER_8: &[u8; 384] = include_bytes!("../tiles_raw/letter-8.bin");
pub static LETTER_9: &[u8; 384] = include_bytes!("../tiles_raw/letter-9.bin");
pub static LETTER_UC_A: &[u8; 384] = include_bytes!("../tiles_raw/letter-A.bin");
pub static LETTER_UC_B: &[u8; 384] = include_bytes!("../tiles_raw/letter-B.bin");
pub static LETTER_UC_C: &[u8; 384] = include_bytes!("../tiles_raw/letter-C.bin");
pub static LETTER_UC_D: &[u8; 384] = include_bytes!("../tiles_raw/letter-D.bin");
pub static LETTER_UC_E: &[u8; 384] = include_bytes!("../tiles_raw/letter-E.bin");
pub static LETTER_UC_F: &[u8; 384] = include_bytes!("../tiles_raw/letter-F.bin");
pub static LETTER_UC_G: &[u8; 384] = include_bytes!("../tiles_raw/letter-G.bin");
pub static LETTER_UC_H: &[u8; 384] = include_bytes!("../tiles_raw/letter-H.bin");
pub static LETTER_UC_I: &[u8; 384] = include_bytes!("../tiles_raw/letter-I.bin");
pub static LETTER_UC_J: &[u8; 384] = include_bytes!("../tiles_raw/letter-J.bin");
pub static LETTER_UC_K: &[u8; 384] = include_bytes!("../tiles_raw/letter-K.bin");
pub static LETTER_UC_L: &[u8; 384] = include_bytes!("../tiles_raw/letter-L.bin");
pub static LETTER_UC_M: &[u8; 384] = include_bytes!("../tiles_raw/letter-M.bin");
pub static LETTER_UC_N: &[u8; 384] = include_bytes!("../tiles_raw/letter-N.bin");
pub static LETTER_UC_O: &[u8; 384] = include_bytes!("../tiles_raw/letter-O.bin");
pub static LETTER_UC_P: &[u8; 384] = include_bytes!("../tiles_raw/letter-P.bin");
pub static LETTER_UC_Q: &[u8; 384] = include_bytes!("../tiles_raw/letter-Q.bin");
pub static LETTER_UC_R: &[u8; 384] = include_bytes!("../tiles_raw/letter-R.bin");
pub static LETTER_UC_S: &[u8; 384] = include_bytes!("../tiles_raw/letter-S.bin");
pub static LETTER_UC_T: &[u8; 384] = include_bytes!("../tiles_raw/letter-T.bin");
pub static LETTER_UC_U: &[u8; 384] = include_bytes!("../tiles_raw/letter-U.bin");
pub static LETTER_UC_V: &[u8; 384] = include_bytes!("../tiles_raw/letter-V.bin");
pub static LETTER_UC_W: &[u8; 384] = include_bytes!("../tiles_raw/letter-W.bin");
pub static LETTER_UC_X: &[u8; 384] = include_bytes!("../tiles_raw/letter-X.bin");
pub static LETTER_UC_Y: &[u8; 384] = include_bytes!("../tiles_raw/letter-Y.bin");
pub static LETTER_UC_Z: &[u8; 384] = include_bytes!("../tiles_raw/letter-Z.bin");
pub static LETTER_LC_A: &[u8; 384] = include_bytes!("../tiles_raw/letter-a.bin");
pub static LETTER_APOSTROPHE: &[u8; 384] = include_bytes!("../tiles_raw/letter-apostrophe.bin");
pub static LETTER_ASTERISC: &[u8; 384] = include_bytes!("../tiles_raw/letter-asterisc.bin");
pub static LETTER_LC_B: &[u8; 384] = include_bytes!("../tiles_raw/letter-b.bin");
pub static LETTER_BACKSLASH: &[u8; 384] = include_bytes!("../tiles_raw/letter-backslash.bin");
pub static LETTER_BOXE: &[u8; 384] = include_bytes!("../tiles_raw/letter-boxe.bin");
pub static LETTER_BOXNE: &[u8; 384] = include_bytes!("../tiles_raw/letter-boxne.bin");
pub static LETTER_BOXNW: &[u8; 384] = include_bytes!("../tiles_raw/letter-boxnw.bin");
pub static LETTER_BOXSE: &[u8; 384] = include_bytes!("../tiles_raw/letter-boxse.bin");
pub static LETTER_BOXSW: &[u8; 384] = include_bytes!("../tiles_raw/letter-boxsw.bin");
pub static LETTER_LC_C: &[u8; 384] = include_bytes!("../tiles_raw/letter-c.bin");
pub static LETTER_CLOUD: &[u8; 384] = include_bytes!("../tiles_raw/letter-cloud.bin");
pub static LETTER_COLON: &[u8; 384] = include_bytes!("../tiles_raw/letter-colon.bin");
pub static LETTER_COMMA: &[u8; 384] = include_bytes!("../tiles_raw/letter-comma.bin");
pub static LETTER_LC_D: &[u8; 384] = include_bytes!("../tiles_raw/letter-d.bin");
pub static LETTER_DARROW: &[u8; 384] = include_bytes!("../tiles_raw/letter-darrow.bin");
pub static LETTER_DOTS: &[u8; 384] = include_bytes!("../tiles_raw/letter-dots.bin");
pub static LETTER_LC_E: &[u8; 384] = include_bytes!("../tiles_raw/letter-e.bin");
pub static LETTER_LC_F: &[u8; 384] = include_bytes!("../tiles_raw/letter-f.bin");
pub static LETTER_FOOD: &[u8; 384] = include_bytes!("../tiles_raw/letter-food.bin");
pub static LETTER_FOOTSTEPS: &[u8; 384] = include_bytes!("../tiles_raw/letter-footsteps.bin");
pub static LETTER_FRONTIER: &[u8; 384] = include_bytes!("../tiles_raw/letter-frontier.bin");
pub static LETTER_LC_G: &[u8; 384] = include_bytes!("../tiles_raw/letter-g.bin");
pub static LETTER_GLASS: &[u8; 384] = include_bytes!("../tiles_raw/letter-glass.bin");
pub static LETTER_GROUND: &[u8; 384] = include_bytes!("../tiles_raw/letter-ground.bin");
pub static LETTER_LC_H: &[u8; 384] = include_bytes!("../tiles_raw/letter-h.bin");
pub static LETTER_HBAR: &[u8; 384] = include_bytes!("../tiles_raw/letter-hbar.bin");
pub static LETTER_HIT: &[u8; 384] = include_bytes!("../tiles_raw/letter-hit.bin");
pub static LETTER_HYPHEN: &[u8; 384] = include_bytes!("../tiles_raw/letter-hyphen.bin");
pub static LETTER_LC_I: &[u8; 384] = include_bytes!("../tiles_raw/letter-i.bin");
pub static LETTER_INTERROGATION: &[u8; 384] =
    include_bytes!("../tiles_raw/letter-interrogation.bin");
pub static LETTER_LC_J: &[u8; 384] = include_bytes!("../tiles_raw/letter-j.bin");
pub static LETTER_LC_K: &[u8; 384] = include_bytes!("../tiles_raw/letter-k.bin");
pub static LETTER_KILL: &[u8; 384] = include_bytes!("../tiles_raw/letter-kill.bin");
pub static LETTER_LC_L: &[u8; 384] = include_bytes!("../tiles_raw/letter-l.bin");
pub static LETTER_LARROW: &[u8; 384] = include_bytes!("../tiles_raw/letter-larrow.bin");
pub static LETTER_LBRACE: &[u8; 384] = include_bytes!("../tiles_raw/letter-lbrace.bin");
pub static LETTER_LBRACKET: &[u8; 384] = include_bytes!("../tiles_raw/letter-lbracket.bin");
pub static LETTER_LDIAG: &[u8; 384] = include_bytes!("../tiles_raw/letter-ldiag.bin");
pub static LETTER_LESS: &[u8; 384] = include_bytes!("../tiles_raw/letter-less.bin");
pub static LETTER_LONGHYPHEN: &[u8; 384] = include_bytes!("../tiles_raw/letter-longhyphen.bin");
pub static LETTER_LPAREN: &[u8; 384] = include_bytes!("../tiles_raw/letter-lparen.bin");
pub static LETTER_LQUOTES: &[u8; 384] = include_bytes!("../tiles_raw/letter-lquotes.bin");
pub static LETTER_LC_M: &[u8; 384] = include_bytes!("../tiles_raw/letter-m.bin");
pub static LETTER_MAGIC: &[u8; 384] = include_bytes!("../tiles_raw/letter-magic.bin");
pub static LETTER_MENHIR: &[u8; 384] = include_bytes!("../tiles_raw/letter-menhir.bin");
pub static LETTER_LC_N: &[u8; 384] = include_bytes!("../tiles_raw/letter-n.bin");
pub static LETTER_LC_O: &[u8; 384] = include_bytes!("../tiles_raw/letter-o.bin");
pub static LETTER_ORB: &[u8; 384] = include_bytes!("../tiles_raw/letter-orb.bin");
pub static LETTER_LC_P: &[u8; 384] = include_bytes!("../tiles_raw/letter-p.bin");
pub static LETTER_PIPE: &[u8; 384] = include_bytes!("../tiles_raw/letter-pipe.bin");
pub static LETTER_PLAYER: &[u8; 384] = include_bytes!("../tiles_raw/letter-player.bin");
pub static LETTER_PLUS: &[u8; 384] = include_bytes!("../tiles_raw/letter-plus.bin");
pub static LETTER_PORTAL: &[u8; 384] = include_bytes!("../tiles_raw/letter-portal.bin");
pub static LETTER_LC_Q: &[u8; 384] = include_bytes!("../tiles_raw/letter-q.bin");
pub static LETTER_QUOTE: &[u8; 384] = include_bytes!("../tiles_raw/letter-quote.bin");
pub static LETTER_QUOTES: &[u8; 384] = include_bytes!("../tiles_raw/letter-quotes.bin");
pub static LETTER_LC_R: &[u8; 384] = include_bytes!("../tiles_raw/letter-r.bin");
pub static LETTER_RARROW: &[u8; 384] = include_bytes!("../tiles_raw/letter-rarrow.bin");
pub static LETTER_RBRACE: &[u8; 384] = include_bytes!("../tiles_raw/letter-rbrace.bin");
pub static LETTER_RBRACKET: &[u8; 384] = include_bytes!("../tiles_raw/letter-rbracket.bin");
pub static LETTER_RDIAG: &[u8; 384] = include_bytes!("../tiles_raw/letter-rdiag.bin");
pub static LETTER_RPAREN: &[u8; 384] = include_bytes!("../tiles_raw/letter-rparen.bin");
pub static LETTER_RQUOTES: &[u8; 384] = include_bytes!("../tiles_raw/letter-rquotes.bin");
pub static LETTER_RUBBLE: &[u8; 384] = include_bytes!("../tiles_raw/letter-rubble.bin");
pub static LETTER_RUNE: &[u8; 384] = include_bytes!("../tiles_raw/letter-rune.bin");
pub static LETTER_LC_S: &[u8; 384] = include_bytes!("../tiles_raw/letter-s.bin");
pub static LETTER_SEMICOLON: &[u8; 384] = include_bytes!("../tiles_raw/letter-semicolon.bin");
pub static LETTER_SLASH: &[u8; 384] = include_bytes!("../tiles_raw/letter-slash.bin");
pub static LETTER_SOUND: &[u8; 384] = include_bytes!("../tiles_raw/letter-sound.bin");
pub static LETTER_SPACE: &[u8; 384] = include_bytes!("../tiles_raw/letter-space.bin");
pub static LETTER_LC_T: &[u8; 384] = include_bytes!("../tiles_raw/letter-t.bin");
pub static LETTER_TICK: &[u8; 384] = include_bytes!("../tiles_raw/letter-tick.bin");
pub static LETTER_TILDE: &[u8; 384] = include_bytes!("../tiles_raw/letter-tilde.bin");
pub static LETTER_TIMES: &[u8; 384] = include_bytes!("../tiles_raw/letter-times.bin");
pub static LETTER_TOTEM: &[u8; 384] = include_bytes!("../tiles_raw/letter-totem.bin");
pub static LETTER_TREE: &[u8; 384] = include_bytes!("../tiles_raw/letter-tree.bin");
pub static LETTER_LC_U: &[u8; 384] = include_bytes!("../tiles_raw/letter-u.bin");
pub static LETTER_UARROW: &[u8; 384] = include_bytes!("../tiles_raw/letter-uarrow.bin");
pub static LETTER_LC_V: &[u8; 384] = include_bytes!("../tiles_raw/letter-v.bin");
pub static LETTER_VBAR: &[u8; 384] = include_bytes!("../tiles_raw/letter-vbar.bin");
pub static LETTER_LC_W: &[u8; 384] = include_bytes!("../tiles_raw/letter-w.bin");
pub static LETTER_WALL: &[u8; 384] = include_bytes!("../tiles_raw/letter-wall.bin");
pub static LETTER_LC_X: &[u8; 384] = include_bytes!("../tiles_raw/letter-x.bin");
pub static LETTER_LC_Y: &[u8; 384] = include_bytes!("../tiles_raw/letter-y.bin");
pub static LETTER_LC_Z: &[u8; 384] = include_bytes!("../tiles_raw/letter-z.bin");
pub static MAP_UC_B: &[u8; 384] = include_bytes!("../tiles_raw/map-B.bin");
pub static MAP_UC_C: &[u8; 384] = include_bytes!("../tiles_raw/map-C.bin");
pub static MAP_UC_D: &[u8; 384] = include_bytes!("../tiles_raw/map-D.bin");
pub static MAP_UC_F: &[u8; 384] = include_bytes!("../tiles_raw/map-F.bin");
pub static MAP_UC_G: &[u8; 384] = include_bytes!("../tiles_raw/map-G.bin");
pub static MAP_UC_H: &[u8; 384] = include_bytes!("../tiles_raw/map-H.bin");
pub static MAP_UC_I: &[u8; 384] = include_bytes!("../tiles_raw/map-I.bin");
pub static MAP_UC_K: &[u8; 384] = include_bytes!("../tiles_raw/map-K.bin");
pub static MAP_UC_L: &[u8; 384] = include_bytes!("../tiles_raw/map-L.bin");
pub static MAP_UC_M: &[u8; 384] = include_bytes!("../tiles_raw/map-M.bin");
pub static MAP_UC_O: &[u8; 384] = include_bytes!("../tiles_raw/map-O.bin");
pub static MAP_UC_P: &[u8; 384] = include_bytes!("../tiles_raw/map-P.bin");
pub static MAP_UC_T: &[u8; 384] = include_bytes!("../tiles_raw/map-T.bin");
pub static MAP_UC_W: &[u8; 384] = include_bytes!("../tiles_raw/map-W.bin");
pub static MAP_LC_A: &[u8; 384] = include_bytes!("../tiles_raw/map-a.bin");
pub static MAP_LC_B: &[u8; 384] = include_bytes!("../tiles_raw/map-b.bin");
pub static MAP_LC_C: &[u8; 384] = include_bytes!("../tiles_raw/map-c.bin");
pub static MAP_CLOUD: &[u8; 384] = include_bytes!("../tiles_raw/map-cloud.bin");
pub static MAP_LC_E: &[u8; 384] = include_bytes!("../tiles_raw/map-e.bin");
pub static MAP_LC_F: &[u8; 384] = include_bytes!("../tiles_raw/map-f.bin");
pub static MAP_FOLIAGE: &[u8; 384] = include_bytes!("../tiles_raw/map-foliage.bin");
pub static MAP_FOOD: &[u8; 384] = include_bytes!("../tiles_raw/map-food.bin");
pub static MAP_FOOTSTEPS: &[u8; 384] = include_bytes!("../tiles_raw/map-footsteps.bin");
pub static MAP_FRONTIER: &[u8; 384] = include_bytes!("../tiles_raw/map-frontier.bin");
pub static MAP_GLASS: &[u8; 384] = include_bytes!("../tiles_raw/map-glass.bin");
pub static MAP_GROUND: &[u8; 384] = include_bytes!("../tiles_raw/map-ground.bin");
pub static MAP_LC_H: &[u8; 384] = include_bytes!("../tiles_raw/map-h.bin");
pub static MAP_HIT: &[u8; 384] = include_bytes!("../tiles_raw/map-hit.bin");
pub static MAP_KILL: &[u8; 384] = include_bytes!("../tiles_raw/map-kill.bin");
pub static MAP_LC_L: &[u8; 384] = include_bytes!("../tiles_raw/map-l.bin");
pub static MAP_MAGIC: &[u8; 384] = include_bytes!("../tiles_raw/map-magic.bin");
pub static MAP_MENHIR: &[u8; 384] = include_bytes!("../tiles_raw/map-menhir.bin");
pub static MAP_LC_N: &[u8; 384] = include_bytes!("../tiles_raw/map-n.bin");
pub static MAP_NOTILE: &[u8; 384] = include_bytes!("../tiles_raw/map-notile.bin");
pub static MAP_ORB: &[u8; 384] = include_bytes!("../tiles_raw/map-orb.bin");
pub static MAP_LC_P: &[u8; 384] = include_bytes!("../tiles_raw/map-p.bin");
pub static MAP_PLAYER: &[u8; 384] = include_bytes!("../tiles_raw/map-player.bin");
pub static MAP_PORTAL: &[u8; 384] = include_bytes!("../tiles_raw/map-portal.bin");
pub static MAP_LC_R: &[u8; 384] = include_bytes!("../tiles_raw/map-r.bin");
pub static MAP_RUBBLE: &[u8; 384] = include_bytes!("../tiles_raw/map-rubble.bin");
pub static MAP_RUNE: &[u8; 384] = include_bytes!("../tiles_raw/map-rune.bin");
pub static MAP_LC_S: &[u8; 384] = include_bytes!("../tiles_raw/map-s.bin");
pub static MAP_SOUND: &[u8; 384] = include_bytes!("../tiles_raw/map-sound.bin");
pub static MAP_SPACE: &[u8; 384] = include_bytes!("../tiles_raw/map-space.bin");
pub static MAP_TICK: &[u8; 384] = include_bytes!("../tiles_raw/map-tick.bin");
pub static MAP_TIMES: &[u8; 384] = include_bytes!("../tiles_raw/map-times.bin");
pub static MAP_TOTEM: &[u8; 384] = include_bytes!("../tiles_raw/map-totem.bin");
pub static MAP_TREE: &[u8; 384] = include_bytes!("../tiles_raw/map-tree.bin");
pub static MAP_LC_V: &[u8; 384] = include_bytes!("../tiles_raw/map-v.bin");
pub static MAP_LC_W: &[u8; 384] = include_bytes!("../tiles_raw/map-w.bin");
pub static MAP_WALL: &[u8; 384] = include_bytes!("../tiles_raw/map-wall.bin");

/// Look up a map tile by character.
pub fn map_tile(ch: char) -> Option<&'static [u8]> {
    match ch {
        '≡' => Some(MAP_CLOUD.as_slice()),
        '"' => Some(MAP_FOLIAGE.as_slice()),
        '%' => Some(MAP_FOOD.as_slice()),
        '♫' => Some(MAP_FOOTSTEPS.as_slice()),
        '¤' => Some(MAP_FRONTIER.as_slice()),
        '◊' => Some(MAP_GLASS.as_slice()),
        '.' => Some(MAP_GROUND.as_slice()),
        '√' => Some(MAP_HIT.as_slice()),
        '∞' => Some(MAP_KILL.as_slice()),
        'Φ' => Some(MAP_MAGIC.as_slice()),
        '&' => Some(MAP_MENHIR.as_slice()),
        '☼' => Some(MAP_ORB.as_slice()),
        '@' => Some(MAP_PLAYER.as_slice()),
        '>' => Some(MAP_PORTAL.as_slice()),
        '^' => Some(MAP_RUBBLE.as_slice()),
        '=' => Some(MAP_RUNE.as_slice()),
        '♪' => Some(MAP_SOUND.as_slice()),
        '!' => Some(MAP_TOTEM.as_slice()),
        '♣' => Some(MAP_TREE.as_slice()),
        '#' => Some(MAP_WALL.as_slice()),
        'B' => Some(MAP_UC_B.as_slice()),
        'C' => Some(MAP_UC_C.as_slice()),
        'D' => Some(MAP_UC_D.as_slice()),
        'F' => Some(MAP_UC_F.as_slice()),
        'G' => Some(MAP_UC_G.as_slice()),
        'H' => Some(MAP_UC_H.as_slice()),
        'I' => Some(MAP_UC_I.as_slice()),
        'K' => Some(MAP_UC_K.as_slice()),
        'L' => Some(MAP_UC_L.as_slice()),
        'M' => Some(MAP_UC_M.as_slice()),
        'O' => Some(MAP_UC_O.as_slice()),
        'P' => Some(MAP_UC_P.as_slice()),
        'T' => Some(MAP_UC_T.as_slice()),
        'W' => Some(MAP_UC_W.as_slice()),
        'a' => Some(MAP_LC_A.as_slice()),
        'b' => Some(MAP_LC_B.as_slice()),
        'c' => Some(MAP_LC_C.as_slice()),
        'e' => Some(MAP_LC_E.as_slice()),
        'f' => Some(MAP_LC_F.as_slice()),
        'h' => Some(MAP_LC_H.as_slice()),
        'l' => Some(MAP_LC_L.as_slice()),
        'n' => Some(MAP_LC_N.as_slice()),
        'p' => Some(MAP_LC_P.as_slice()),
        'r' => Some(MAP_LC_R.as_slice()),
        's' => Some(MAP_LC_S.as_slice()),
        'v' => Some(MAP_LC_V.as_slice()),
        'w' => Some(MAP_LC_W.as_slice()),
        _ => None,
    }
}

/// Look up a letter tile by character.
pub fn letter_tile(ch: char) -> Option<&'static [u8]> {
    match ch {
        '’' => Some(LETTER_APOSTROPHE.as_slice()),
        '*' => Some(LETTER_ASTERISC.as_slice()),
        '\\' => Some(LETTER_BACKSLASH.as_slice()),
        '┤' => Some(LETTER_BOXE.as_slice()),
        '┐' => Some(LETTER_BOXNE.as_slice()),
        '┌' => Some(LETTER_BOXNW.as_slice()),
        '┘' => Some(LETTER_BOXSE.as_slice()),
        '└' => Some(LETTER_BOXSW.as_slice()),
        '≡' => Some(LETTER_CLOUD.as_slice()),
        ':' => Some(LETTER_COLON.as_slice()),
        ',' => Some(LETTER_COMMA.as_slice()),
        '↓' => Some(LETTER_DARROW.as_slice()),
        '…' => Some(LETTER_DOTS.as_slice()),
        '%' => Some(LETTER_FOOD.as_slice()),
        '♫' => Some(LETTER_FOOTSTEPS.as_slice()),
        '¤' => Some(LETTER_FRONTIER.as_slice()),
        '◊' => Some(LETTER_GLASS.as_slice()),
        '.' => Some(LETTER_GROUND.as_slice()),
        '─' => Some(LETTER_HBAR.as_slice()),
        '√' => Some(LETTER_HIT.as_slice()),
        '-' => Some(LETTER_HYPHEN.as_slice()),
        '?' => Some(LETTER_INTERROGATION.as_slice()),
        '∞' => Some(LETTER_KILL.as_slice()),
        '←' => Some(LETTER_LARROW.as_slice()),
        '{' => Some(LETTER_LBRACE.as_slice()),
        '[' => Some(LETTER_LBRACKET.as_slice()),
        '«' => Some(LETTER_LDIAG.as_slice()),
        '<' => Some(LETTER_LESS.as_slice()),
        '—' => Some(LETTER_LONGHYPHEN.as_slice()),
        '(' => Some(LETTER_LPAREN.as_slice()),
        '“' => Some(LETTER_LQUOTES.as_slice()),
        'Φ' => Some(LETTER_MAGIC.as_slice()),
        '&' => Some(LETTER_MENHIR.as_slice()),
        '☼' => Some(LETTER_ORB.as_slice()),
        '|' => Some(LETTER_PIPE.as_slice()),
        '@' => Some(LETTER_PLAYER.as_slice()),
        '+' => Some(LETTER_PLUS.as_slice()),
        '>' => Some(LETTER_PORTAL.as_slice()),
        '\'' => Some(LETTER_QUOTE.as_slice()),
        '"' => Some(LETTER_QUOTES.as_slice()),
        '→' => Some(LETTER_RARROW.as_slice()),
        '}' => Some(LETTER_RBRACE.as_slice()),
        ']' => Some(LETTER_RBRACKET.as_slice()),
        '»' => Some(LETTER_RDIAG.as_slice()),
        ')' => Some(LETTER_RPAREN.as_slice()),
        '”' => Some(LETTER_RQUOTES.as_slice()),
        '^' => Some(LETTER_RUBBLE.as_slice()),
        '=' => Some(LETTER_RUNE.as_slice()),
        ';' => Some(LETTER_SEMICOLON.as_slice()),
        '/' => Some(LETTER_SLASH.as_slice()),
        '♪' => Some(LETTER_SOUND.as_slice()),
        ' ' => Some(LETTER_SPACE.as_slice()),
        '•' => Some(LETTER_TICK.as_slice()),
        '~' => Some(LETTER_TILDE.as_slice()),
        '×' => Some(LETTER_TIMES.as_slice()),
        '!' => Some(LETTER_TOTEM.as_slice()),
        '♣' => Some(LETTER_TREE.as_slice()),
        '↑' => Some(LETTER_UARROW.as_slice()),
        '│' => Some(LETTER_VBAR.as_slice()),
        '#' => Some(LETTER_WALL.as_slice()),
        '0' => Some(LETTER_0.as_slice()),
        '1' => Some(LETTER_1.as_slice()),
        '2' => Some(LETTER_2.as_slice()),
        '3' => Some(LETTER_3.as_slice()),
        '4' => Some(LETTER_4.as_slice()),
        '5' => Some(LETTER_5.as_slice()),
        '6' => Some(LETTER_6.as_slice()),
        '7' => Some(LETTER_7.as_slice()),
        '8' => Some(LETTER_8.as_slice()),
        '9' => Some(LETTER_9.as_slice()),
        'A' => Some(LETTER_UC_A.as_slice()),
        'B' => Some(LETTER_UC_B.as_slice()),
        'C' => Some(LETTER_UC_C.as_slice()),
        'D' => Some(LETTER_UC_D.as_slice()),
        'E' => Some(LETTER_UC_E.as_slice()),
        'F' => Some(LETTER_UC_F.as_slice()),
        'G' => Some(LETTER_UC_G.as_slice()),
        'H' => Some(LETTER_UC_H.as_slice()),
        'I' => Some(LETTER_UC_I.as_slice()),
        'J' => Some(LETTER_UC_J.as_slice()),
        'K' => Some(LETTER_UC_K.as_slice()),
        'L' => Some(LETTER_UC_L.as_slice()),
        'M' => Some(LETTER_UC_M.as_slice()),
        'N' => Some(LETTER_UC_N.as_slice()),
        'O' => Some(LETTER_UC_O.as_slice()),
        'P' => Some(LETTER_UC_P.as_slice()),
        'Q' => Some(LETTER_UC_Q.as_slice()),
        'R' => Some(LETTER_UC_R.as_slice()),
        'S' => Some(LETTER_UC_S.as_slice()),
        'T' => Some(LETTER_UC_T.as_slice()),
        'U' => Some(LETTER_UC_U.as_slice()),
        'V' => Some(LETTER_UC_V.as_slice()),
        'W' => Some(LETTER_UC_W.as_slice()),
        'X' => Some(LETTER_UC_X.as_slice()),
        'Y' => Some(LETTER_UC_Y.as_slice()),
        'Z' => Some(LETTER_UC_Z.as_slice()),
        'a' => Some(LETTER_LC_A.as_slice()),
        'b' => Some(LETTER_LC_B.as_slice()),
        'c' => Some(LETTER_LC_C.as_slice()),
        'd' => Some(LETTER_LC_D.as_slice()),
        'e' => Some(LETTER_LC_E.as_slice()),
        'f' => Some(LETTER_LC_F.as_slice()),
        'g' => Some(LETTER_LC_G.as_slice()),
        'h' => Some(LETTER_LC_H.as_slice()),
        'i' => Some(LETTER_LC_I.as_slice()),
        'j' => Some(LETTER_LC_J.as_slice()),
        'k' => Some(LETTER_LC_K.as_slice()),
        'l' => Some(LETTER_LC_L.as_slice()),
        'm' => Some(LETTER_LC_M.as_slice()),
        'n' => Some(LETTER_LC_N.as_slice()),
        'o' => Some(LETTER_LC_O.as_slice()),
        'p' => Some(LETTER_LC_P.as_slice()),
        'q' => Some(LETTER_LC_Q.as_slice()),
        'r' => Some(LETTER_LC_R.as_slice()),
        's' => Some(LETTER_LC_S.as_slice()),
        't' => Some(LETTER_LC_T.as_slice()),
        'u' => Some(LETTER_LC_U.as_slice()),
        'v' => Some(LETTER_LC_V.as_slice()),
        'w' => Some(LETTER_LC_W.as_slice()),
        'x' => Some(LETTER_LC_X.as_slice()),
        'y' => Some(LETTER_LC_Y.as_slice()),
        'z' => Some(LETTER_LC_Z.as_slice()),
        _ => None,
    }
}
